services:
  - type: web
    name: trade-journal-database
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm ci
    startCommand: npm run migrate && node index.js
    envVars:
      - key: PGDATABASE
        fromDatabase:
          name: trade-journal-database
          property: database
      - key: PGUSER
        fromDatabase:
          name: trade-journal-database
          property: user
      - key: PGPASSWORD
        fromDatabase:
          name: trade-journal-database
          property: password
      - key: PGHOST
        fromDatabase:
          name: trade-journal-database
          property: host
      - key: PGPORT
        fromDatabase:
          name: trade-journal-database
          property: port
databases:
  - name: trade-journal-database
    plan: free
    region: frankfurt
    databaseName: trade_journal_dev
    ipAllowList: []
